services:
  - type: web
    name: nyayai-backend
    env: node
    rootDir: server
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 10000
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: qwen/qwen3.6-27b
      - key: AGORA_APP_ID
        value: 289ce9c667fa4a64b22c36475d828ab1
      - key: AGORA_APP_CERTIFICATE
        sync: false
      - key: JWT_SECRET
        value: nyayai-production-secret-key-2026-super-secure-jwt
